---
title: "LikertGraph"
author: "Vorisek_CN and Paula Josephine Mayer"
date: "26 3 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(likert)
library(magrittr)
library(mosaic)
library(HH)
library(RColorBrewer)
library(dplyr)
library(ggplot2)
```

##reading Data from csv file
```{r}
d_gesamt3 <- read.csv2("LikertGraph.csv")
d_gesamt3 <-rename(d_gesamt3, "Not fair at all" = Not.fair.at.all,"Barely Fair"=Barely.fair, "Moderately Fair" = Moderately.fair, "Very fair"= Very.Fair)
type2 <- c("Gender","Gender","Gender","Gender","Age","Age","Age","Age","Environment","Environment","Environment")
d_gesamt_new3 <- cbind(d_gesamt3, type2)
```

##likert Plot
```{r}
likert(Item~. | type2, d_gesamt_new3, main = list("How would you rate the level of fairness of AI in your AI development?"), layout=c(1,3),scales=list(y=list(relation="free")),col = brewer.pal(n=6,"RdYlBu"), between=list(y=1),par.strip.text=list(cex=1.1, lines=1), strip.left=TRUE, strip = FALSE, as.percent=TRUE,xlab="Percentage",ylab="")
```

